[workspace]
resolver = "3"
members = ["rusty-cdk", "rusty-cdk-core", "rusty-cdk-macros", "iam-docs-scraper", "examples/apigateway_lambda_dynamodb", "examples/app_config_and_secrets_with_two_lambdas"]
