[package]
name = "example"
version = "0.4.0"
edition = "2024"

[dependencies]
aws_lambda_events = "0.18.0"
tokio = { version = "1.46.1", features = ["full"] }
aws-config = { version = "1.8.1" }
aws-sdk-dynamodb = "1.93.0"
lambda_runtime = "0.13.0"